---
title: "Data Cleaning: Science Funding Dynamics"
author: "Kristin Keith"
date: "2025-11-12"
output: html_document
---

This .Rmd assumes the working directory is the project root and that raw CSVs are stored in data/raw/.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages}
library(tidyverse)
library(ggplot2)
library(lubridate)   # date handling
library(janitor)     # clean_names()
library(here)        # safe relative paths

# set seed for sampling
set.seed(123)

```

```{r merge data}
# list all raw files 
raw_files <- list.files(here("data", "raw"),
                        pattern = "PrimeAwardSummaries_\\d{4}\\.csv",
                        full.names = TRUE)
raw_files

# read all CSVs and combine into one dataframe 
grants_raw <- raw_files %>% 
  map_dfr(~ read_csv(.x, show_col_types = FALSE) %>% clean_names()) # clean_names() to ensure everything lowercase

glimpse(grants_raw)
  
```
```{r filter agencies}

# filter to specific science funding agencies; I initially did this in retrieving the data, but want to ensure that only these organizations are in the full dataframe 
science_agencies <- c("Department of Health and Human Services",
  "National Science Foundation",
  "Department of Energy",
  "National Aeronautics and Space Administration",
  "Department of Agriculture",
  "Environmental Protection Agency",
  "Department of Defense")

grants_science <- grants_raw %>%
  mutate(awarding_agency_name = str_squish(awarding_agency_name)) %>% # remove extra spaces 
  filter(awarding_agency_name %in% science_agencies) # keep only specific science funding agencies 

# view the number of grants per agency in merged dataset 
grants_science %>%
  count(awarding_agency_name)

```
```{r quick visualizations}

# bar chart of number of grants per agency, reordered from largest -> smallest 
grants_science %>%
  count(awarding_agency_name) %>%
  ggplot(aes(x = reorder(awarding_agency_name, n), y = n)) +
  geom_col(fill = "lightpink") +
  coord_flip() +
  labs(title = "Number of Grants by Agency",
    x = "Agency",
    y = "Number of Grants")

# histogram of total_obligated_amount across all grants regardless of agency (a glimpse at how financially big science grants are)
grants_science %>%
  ggplot(aes(x = total_obligated_amount)) + 
  geom_histogram(bins = 60, fill = "lightpink", color = "white") +
  scale_x_log10() + # use log10 scale due to extremely large grant award outliers skewing the data (right skew)
  theme_minimal() +
  labs(title = "Total Obligated Amounts for All Science Grants (Log Scale)",
    x = "Total Obligated Amount",
    y = "Number of Grants")

# boxplot of total_obligated_amount per award agency  
grants_science %>%
  filter(total_obligated_amount > 0) %>%  # can't have negative values 
  ggplot(aes(x = awarding_agency_name, y = total_obligated_amount)) +
  geom_boxplot(outlier.alpha = 0.2, fill = "lightpink") +
  scale_y_log10() +  # log scale to adjust for extreme award outliers (right skew)
  coord_flip() +
  theme_minimal() +
  labs(title = "Distribution of Award Amounts by Agency (Log Scale)",
    x = "Agency",
    y = "Total Obligated Amount")
```

```{r scatterplot}
# scatterplot to show relationship between grant duration and obligated amount 
# calculate grant duration in days
grants_science <- grants_science %>%
  mutate(duration_days = as.numeric(period_of_performance_current_end_date - period_of_performance_start_date))

grants_duration <- grants_science %>%
  filter(!is.na(duration_days),
         !is.na(total_obligated_amount)) %>% # remove NA rows 
  filter(duration_days > 0,
         total_obligated_amount > 0) %>% # remove negative durations 
  filter(duration_days <= 3650)  #drop impossible durations 

set.seed(123)  # reproducible sampling for the report

# take subset of data 
grants_duration_sample <- grants_duration %>%
  dplyr::sample_n(50000) 

grants_duration_sample %>%
  ggplot(aes(x = duration_days, y = total_obligated_amount)) +
  geom_point(alpha = 0.1, color = "hotpink") +  # transparency to reduce overplotting
  scale_y_log10(labels = scales::comma) +
  theme_minimal() +
  labs(title = "Relationship Between Grant Duration and Funding Amount",
    x = "Duration of Grant (days)",
    y = "Total Obligated Amount (log10)")
```
